### ISSUE TITLE
Лишний див

### ISSUE THREAD

**Issue by pecourses** [Alex-it-work/CSS-homework#1]
https://github.com/Alex-it-work/CSS-homework/blob/6ebe00cfcd089fc60a475c08f14729d0511b8f8b/index.html#L13
- В принципе, тут нет необходимости использовать дополнительный div, все коректно бы отработало, если бы во внешний класс поставить свойство для выравнивания по центру. Лишние обертки не улучшают читабельность.

**Comment by Alex-it-work** [comment]
fixed
